title: nwienert
url: http://natewienert.com
name: Metta World Peace
tagline: I'm fucking awesome!
twitter: natebirdman
github: http://github.com/natew
email: natewienert@gmail.com
login: nwienert
password: fluf499