---
title:               This is a blog.
tagline:             This is not a clever tagline.
login:               <%= ENV["blog_login"] ? ENV["blog_login"] : "user" %>
password:            <%= ENV["blog_password"] ? ENV["blog_password"] : "password" %>
name:                Matthew DuVall
twitter:             maskact
github:              maskact
email:               mduvall@berkeley.edu
google_analytics_id: YOUR_GA_ID
