title: Scott Klein
name: Scott Klein
tagline: Musings on life, startups, and code.
twitter: scootklein
github: http://github.com/scootklein
email: scott@scottkle.in
google_analytics_id: UA-21155180-1
login: scott
password: sc0ttBL0G
