title: nwienert
url: http://0.0.0.0:3000
name: Metta World Peace
tagline: I'm fucking awesome!
twitter: natebirdman
github: http://github.com/NateW
email: natewienert@gmail.com
login: username
password: password