---
title:               This is a blog.
tagline:             This is not a clever tagline.
login:               <%= ENV["blog_login"] %>
password:            <%= ENV["blog_password"] %>
name:                Matthew DuVall
twitter:             maskact
github:              maskact
email:               mduvall@berkeley.edu
google_analytics_id: YOUR_GA_ID
