# Your information
name:    Your Name
tagline:
twitter: handle
github:  username
email:   me@example.com

# Google Analytics
ga_id:   UA-XXXXXXXX-X

# Admin credentials
login:    <%= ENV["obtvse_login"] ? ENV["obtvse_login"] : "username" %>
password: <%= ENV["obtvse_password"] ? ENV["obtvse_password"] : "password" %>

# Amazon S3
access_key_id:     <%= ENV["access_key_id"] ? ENV["access_key_id"] : "" %>
secret_access_key: <%= ENV["secret_access_key"] ? ENV["secret_access_key"] : "" %>
bucket:            bucket_name