<% def env(a, b); e = ENV["obtvse_#{a}"]; e ? e : b; end %>

# Your information
name:    <%= env :name,    'Your Name' %>
twitter: <%= env :twitter, 'handle' %>
github:  <%= env :github,  'username'  %>
email:   <%= env :email,   'me@example.com'  %>

# Google Analytics
ga_id:   <%= env :ga,      'UA-XXXXXXXX-X'  %>